### ISSUE TITLE
Can use optionally Fortune : Improvement

### ISSUE THREAD

**Issue by xypnox** [TheMousePotato/muse#1]
Hi, I haven't tried the App but it can use the "[fortune](https://en.wikipedia.org/wiki/Fortune_(Unix))" command for not just quotes... 

Also use `-s` with fortune to get short quotations only

**Comment by themousepotato** [comment]
@xypnox Thanks for showing interest in the project. It seems like GPL v3 is [compatible](https://www.gnu.org/licenses/license-list.en.html#FreeBSD) with FreeBSD. Even though I'm not a fan of non-copyleft licenses, the technical advantage and compatibility make me interested. I would love to see a PR from you.

**Comment by themousepotato** [comment]
Implemented by @MuLx10 . Closing.
